version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aether
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./mud-schema-v2.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  postgres_data:
